server:
  port: 9999

spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://mysql:3306/uaa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  ldap:
    urls: ldap://ldap:389
    base: dc=luban,dc=com
    username: cn=admin,dc=luban,dc=com
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.luban.uaa: DEBUG

# GitHub OAuth2配置 (需要替换为实际值)
spring.security.oauth2.client.registration.github.client-id=YOUR_GITHUB_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_GITHUB_CLIENT_SECRET

# JWT配置
jwt:
  secret: luban-springcloud-demo-secret-key-for-jwt-token-generation-must-be-long-enough
  expiration: 86400000
